### ISSUE TITLE
Building fails despite latest tinyxml (Linux Mint 17.3 / Ubuntu 14.04.5)

### ISSUE THREAD

**Issue by ginsterbusch** [tolga9009/sidewinderd#20]
Both building with the latest commit and release 0.4.0 fails under Linux Mint 17.3 (aka Ubuntu 14.04.5 LTS):

```
/home/fwolf/inst/sources/logitech-g710/sidewinderd/sidewinderd-0.4.0/src/core/keyboard.cpp: In member function ‘void Keyboard::recordMacro(std::string, Led*, int)’:
/home/fwolf/inst/sources/logitech-g710/sidewinderd/sidewinderd-0.4.0/src/core/keyboard.cpp:125:17: error: ‘class tinyxml2::XMLElement’ has no member named ‘SetText’
     DelayEvent->SetText(static_cast<int>(delay));
                 ^
/home/fwolf/inst/sources/logitech-g710/sidewinderd/sidewinderd-0.4.0/src/core/keyboard.cpp:138:19: error: ‘class tinyxml2::XMLElement’ has no member named ‘SetText’
    KeyBoardEvent->SetText(inev.code);
```

Installed dependencies:
- libconfig: 1.4.9-2 (package: libconfig++9)
- tinyxml2: 2.6.2 (package: libtinyxml2.6.2)
- libudev: 204-5ubuntu20 (package: libudev-dev)

cu, w0lf.

**Comment by ginsterbusch** [comment]
Note: There is no newer libudev. At least not on 14.04. And I wouldnt want to compromise my otherwise very stable system.

cu, w0lf.

**Comment by tolga9009** [comment]
Hi,

you've installed TinyXML*1* version 2.6.2. But you need to install TinyXML2 (current version: 4.x): https://launchpad.net/ubuntu/+source/tinyxml2

They are 2 different libraries. I know, it's a bit confusing, but the naming / versioning of TinyXML2 wasn't my idea :).

What I don't get is, that CMake doesn't throw an error, but the compiler is. I will look, if I can get a better search for TinyXML2 libraries.

Report back, if there are any other issues or the issue persists.

Cheers,
Tolga

**Comment by ginsterbusch** [comment]
> you've installed TinyXML1 version 2.6.2. But you need to install TinyXML2 (current version: 4.x): https://launchpad.net/ubuntu/+source/tinyxml2

nasty. got myself the proper backports repository added (after figuring out that checking "backports" in synaptic didnt work as expected; probably some Linux Mint idiocy backfiring), installed version 2.1 .. now let's see if THAT helps ;)

cu, w0lf.

**Comment by ginsterbusch** [comment]
Ok, seems to work now. Had to change some settings with checkinstall before building the package to avoid overwriting a preexisting package.

Maybe you want to add that as build instructions for GNU/Debian and Ubuntu .. ;)

cu, w0lf.

**Comment by tolga9009** [comment]
Hi there,

glad you got it working! Yeah, I really don't understand, why they made the naming scheme is so damn confusing. There are:
* `libtinyxml2-0.0.0` (trusty universe, not working)
* `libtinyxml2-2` (trusty backports, works)
* `libtinyxml2-2v5` (xenial universe, works)
* `libtinyxml2-4` (yakkety universe, works)
* `libtinyxml2.6.2` (trusty universe, **doesn't work**, this is TinyXML1)
* `libtinyxml2.6.2v5` (xenial universe, **doesn't work**, this is TinyXML1)

Even CMake gets confused and reports a false positive for TinyXML2 library. This is why I was thinking about dropping `TinyXML2` and `libconfig++` altogether and using `jsoncpp`

**Comment by ginsterbusch** [comment]
I wouldn't call GNU/Debian and Ubuntu "various" distros, but a simple wiki entry might do. ~~I certainly don't know how to create a PPA,~~ .. If I get sidewinderd working under Linux Mint 17.3 aka "pimped" Ubuntu 14.04.5 LTS (because there is no systemd!), I'm considering setting one up for Ubuntu, and maybe Debian 8, too.

cu, w0lf.

**Comment by tolga9009** [comment]
Don't get me wrong, I was generally talking about differencies in Linux distributions (and package naming), I can't include package names for all of them. If CentOS calls their `apache` service `httpd`, it's not my job to make things clear for CentOS users in my distribution-independent documentation.

Here on GitHub, I'm a software developer, not a package maintainer. In terms of documentation, I think it's understandable, which libraries this software depends on (TinyXML2,  and which commands need to be executed, in order to build.

That aside, I think it's a much greater help for new (Linux Mint / Ubuntu / Debian) users to create a PPA and / or a `.deb` for them, which installs with a single command or single click.

About no systemd: that shouldn't be a problem, as long as udev is available. Just use an init script, which launches `sidewinderd -d` on boot (`-d` flag for "legacy" daemon mode. _Note: not needed for systemd users. as it automatically takes care of that_). Fedora / CentOS 7 / Ubuntu 16.04 and Debian Jessie all use systemd and shouldn't need any adjustments.

I'll look into setting up Ubuntu PPAs aswell.

Cheers,
Tolga

**Comment by salman2learn** [comment]
For ubuntu 16.04 fresh install, this set worked for me:
sudo apt install cmake libconfig++8-dev libtinyxml2-dev libudev-dev

Thanks.

**Comment by tolga9009** [comment]
Thank you @salman2learn! Based on your post, I've added basic instructions to the Wiki for Ubuntu 16.04.x LTS. Feel free to improve!

PPA would still be the best solution, but didn't have success so far. Either way, I'm closing this issue, as we have the exact commands for Ubuntu users now and they should do the trick.

Cheers,
Tolga
