### ISSUE TITLE
sidewinderd.service is hard-coded to use /usr/bin

### ISSUE THREAD

**Issue by tolga9009** [tolga9009/sidewinderd#5]
On some systems, /usr/local/bin needs to be taken instead, or the service will fail to start. Thanks to arunce from ubuntu forums. Original bug report: http://ubuntuforums.org/showthread.php?t=1543370&page=6&p=13278148#post13278148

**Comment by tolga9009** [comment]
One possible fix: rename sidewinderd.service to sidewinderd.service.in and preprocess it, using CMake configure_file(). Replace "/usr" by DCMAKE_INSTALL_PREFIX macro and voila, the service file should be correctly adjusted. I'm gonna fix it this weekend.

**Comment by aldevel** [comment]
Really good to see that you still work on this GREAT driver. Currently, I try to use it on Debian 8.2 for G710 and I faced with this problem too. Sorry for my ignorance but I don't really see actually what should be renamed, where and when (before or after installation). Rename the file in sidewinderd-lg-g710/etc/ and change the soruce in sidewinderd-lg-g710/src/CMakeLists.txt in line "ADD_EXECUTABLE" before installation? I think, the only solution for me and It would be better if I wait for your version instead, I think :).
Thanks a lot for this project!!

**Comment by tolga9009** [comment]
Glad to see, that there are actually people using it!

I didn't want to confuse you. The solution above is for automating the installation process, so installation is as smooth as possible. But it's not needed - you can also edit the files on your own.

If you haven't run `make` and `make install` yet, edit `sidewinderd.service` in this project's `etc` directory. Adjust `ExecStart` according to your needs. On my system, the correct path is `/usr/bin/sidewinderd`, but on others, the correct path is `/usr/local/bin/sidewinderd` or even something else. Just find out, where sidewinderd gets installed (e.g. by using `find /usr/ -name "*sidewinderd*"`).

If you have already run `make` and `make install`, find the installed `sidewinderd.service` in `/usr/lib/systemd/system/`, open and edit it. If this folder doesn't exist on your system, try finding the file manually by using the command above.

After fixing this issue, these additional steps won't be needed on your system. It will be easy as using `make` and `make install`.

Hope this helps!

Cheers,
Tolga

**Comment by aldevel** [comment]
Thanks for your prompt response!
It assured me that your driver is perfect and something else setting or deficiency cause the boot problem. Maybe it helps somebody that my problem was the iogear gbu521 bluetooth adapter. To solve the other usb interfaces booting problem just plug off this adapter, reboot and after that plug it in again. To solve iogear gbu521 firmware problem, you need to focus on broadcom's BCM20702A0 driver. For me, this was the solution: http://plugable.com/2014/06/23/plugable-usb-bluetooth-adapter-solving-hfphsp-profile-issues-on-linux. Altough I found the final solution in comments that I had to rename the firmware file to BCM920702 Bluetooth 4.0-0a5c-21e8.hcd instead of BCM20702A0-0a5c-21e8.hcd for my system.
Please inform me if this comment shouldn't be in this issue or just remove it.
Thank you again for sidewinderd driver!

**Comment by tolga9009** [comment]
Thanks for your feedback! Good to know, something else was causing the trouble. I'll leave the comment there, as other people might suffer from similar issues. Thanks for sharing!

Cheers,
Tolga

**Comment by tolga9009** [comment]
Fixed by 91eff12bf5e9a74b323313eef2a84cd3353b7add. If needed, use `-DCMAKE_INSTALL_PREFIX` flag for customization. Closing.

Cheers,
Tolga
