### ISSUE TITLE
initial LEDs are not set on start

### ISSUE THREAD

**Issue by tolga9009** [tolga9009/sidewinderd#8]
After adding support for the Logitech G710+, I've forgotten a small piece of code in the constructor for setting up the initial LEDs. The intended behaviour is, that the profile LED should light up after starting sidewinderd (defaults to profile 1; can be set in .conf file). But currently, the LED profile only lights up, after pressing one of the LED buttons.

Fix is coming. Gonna update to 0.3.1 aswell.

Cheers,
Tolga

**Comment by aldevel** [comment]
Thanks, this service gonna be better and better. I would like to note here if somebody experience that Scroll Lock key or led doesn't work than it isn't related to Sidewinderd service. In Debian 8.2, I solved this in /usr/share/X11/xkb/symbolus/us (or use any of your language instead of "us"):
modifier_map Mod3   { Scroll_Lock }; <==<< Add this line
include "level3(ralt_switch)" <==<< before this line
I found this solution here:
http://askubuntu.com/questions/127167/how-do-i-enable-scroll-lock
and here:
http://www.pclinuxos.com/forum/index.php/topic,125690.msg1052201.html?PHPSESSID=2qsv83lve6dgd0ivq14bfcjc30#msg1052201

**Comment by tolga9009** [comment]
Issue fixed by 15a7a6771bb391abb26f161a41809bbbc1d586e6. Closing.

Cheers,
Tolga
